#!/bin/bash
# Quick reference for image locations and replacement

echo "=========================================="
echo "TIT Website - Premium Images Overview"
echo "=========================================="
echo ""
echo "WORK PAGE IMAGES (800x600 pixels)"
echo "Location: /public/work/"
echo ""
echo "✓ ai-ecommerce-platform.jpg"
echo "  └─ Project: AI-Powered E-Commerce Revolution"
echo "  └─ Category: Web Development"
echo "  └─ Theme Color: Blue (#2563eb)"
echo ""
echo "✓ brand-identity-system.jpg"
echo "  └─ Project: Brand Identity System"
echo "  └─ Category: Branding"
echo "  └─ Theme Color: Purple (#8b5cf6)"
echo ""
echo "✓ social-media-campaign.jpg"
echo "  └─ Project: Viral Social Media Campaign"
echo "  └─ Category: Marketing"
echo "  └─ Theme Color: Pink (#ec4899)"
echo ""
echo "✓ mobile-app-design.jpg"
echo "  └─ Project: Mobile App Design Excellence"
echo "  └─ Category: UI/UX Design"
echo "  └─ Theme Color: Cyan (#06b6d4)"
echo ""
echo "✓ product-packaging.jpg"
echo "  └─ Project: Premium Product Packaging"
echo "  └─ Category: Design"
echo "  └─ Theme Color: Amber (#f59e0b)"
echo ""
echo "✓ corporate-website.jpg"
echo "  └─ Project: Corporate Website Redesign"
echo "  └─ Category: Web Development"
echo "  └─ Theme Color: Green (#10b981)"
echo ""
echo "=========================================="
echo "BLOG PAGE IMAGES (1200x630 pixels)"
echo "Location: /public/blog/"
echo ""
echo "✓ ai-marketing-future.jpg"
echo "  └─ Article: The Future of Marketing is AI"
echo "  └─ Category: AI & Marketing"
echo "  └─ Theme Color: Purple (#8b5cf6)"
echo ""
echo "✓ seo-trends-2025.jpg"
echo "  └─ Article: SEO Trends 2025"
echo "  └─ Category: SEO Strategy"
echo "  └─ Theme Color: Blue (#2563eb)"
echo ""
echo "✓ social-media-roi.jpg"
echo "  └─ Article: Maximizing Social Media ROI"
echo "  └─ Category: Social Media"
echo "  └─ Theme Color: Pink (#ec4899)"
echo ""
echo "✓ personal-branding.jpg"
echo "  └─ Article: Personal Branding for Experts"
echo "  └─ Category: Personal Brand"
echo "  └─ Theme Color: Amber (#f59e0b)"
echo ""
echo "✓ content-strategy-10x.jpg"
echo "  └─ Article: Content Strategy: 10x Results"
echo "  └─ Category: Content"
echo "  └─ Theme Color: Green (#10b981)"
echo ""
echo "✓ design-psychology.jpg"
echo "  └─ Article: Design Psychology"
echo "  └─ Category: Design"
echo "  └─ Theme Color: Cyan (#06b6d4)"
echo ""
echo "=========================================="
echo "TO REPLACE IMAGES:"
echo "=========================================="
echo ""
echo "1. Find new images (stock photos or AI-generated)"
echo "2. Resize to correct dimensions:"
echo "   - Work: 800x600"
echo "   - Blog: 1200x630"
echo "3. Save with the exact same filename"
echo "4. Files will update automatically"
echo ""
echo "=========================================="
echo "RECOMMENDED SOURCES:"
echo "=========================================="
echo ""
echo "Stock Photos (Free):"
echo "  • Unsplash.com"
echo "  • Pexels.com"
echo "  • Pixabay.com"
echo ""
echo "Stock Photos (Premium):"
echo "  • Shutterstock.com"
echo "  • Adobe Stock"
echo "  • iStock"
echo ""
echo "AI Image Generation:"
echo "  • Midjourney (best quality)"
echo "  • DALL-E 3"
echo "  • Adobe Firefly"
echo "  • Runway ML"
echo ""
echo "Design Tools (for custom covers):"
echo "  • Canva"
echo "  • Figma"
echo "  • Adobe Express"
echo "  • Photopea"
echo ""
echo "=========================================="
